[package]
name = "shared"
version = "0.0.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
regex = "1.9.5"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.3.0"
thiserror = "1.0.48"
